[settings]
auto_env = true

[settings.github]
credential_command = "gh auth token"

[tools]
bat = "latest"
bottom = "latest"
delta = "latest"
eza = "latest"
fzf = "latest"
java = "temurin-17"
jq = "latest"
node = "lts"
ripgrep = "latest"
terraform = "latest"
uv = "latest"
starship = "latest"
sccache = "latest"
dust = "latest"
gitui = "latest"
go = "latest"
neovim = "latest"
lua = "latest"
tmux = "latest"
tree-sitter = "latest"
fd = "latest"
gdu = "latest"
caddy = "latest"
step = "latest"
rust = "latest"
